kibana_version: "8.13.4"
kibana_apt_repo: "deb [signed-by=/usr/share/keyrings/elasticsearch.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
kibana_server_host: "0.0.0.0"
kibana_elasticsearch_url: "http://localhost:9200"
