- name: Install required dependencies
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: "{{ grafana_apt_key_url }}"
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "{{ grafana_repo }}"
    state: present
    filename: grafana

- name: Install Grafana package
  ansible.builtin.apt:
    name: "{{ grafana_apt_package }}"
    state: present
    update_cache: true

- name: Ensure Grafana is enabled and started
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true
