- name: Ensure Docker Compose directory exists
  ansible.builtin.file:
    path: "{{ registry_compose_path }}"
    state: directory
    mode: '0644'

- name: Copy compose resources
  ansible.builtin.template:
    src: daemon.json.jinja2
    dest: "{{ registry_compose_path }}/daemon.json"
    mode: preserve

- name: Deploy Jenkins Agent Compose config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
  with_items:
    - src: docker-compose.yml.jinja2
      dest: "{{ registry_compose_path }}/docker-compose.yml"
    - src: templates/default_docker_compose_service.yml.j2
      dest: "{{ services_path }}/{{ compose_service_name }}"

- name: Run compose service
  ansible.builtin.systemd:
    name: "{{ compose_service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
