- name: Ensure Docker Compose directory exists
  ansible.builtin.file:
    path: "{{ registry_compose_path }}"
    state: directory
    mode: '0644'

- name: Deploy Jenkins Agent Compose config
  ansible.builtin.template:
    src: docker-compose.yml.jinja2
    dest: "{{ registry_compose_path }}/docker-compose.yml"
    mode: preserve

- name: Copy compose resources
  ansible.builtin.template:
    src: daemon.json.jinja2
    dest: "{{ registry_compose_path }}/daemon.json"
    mode: preserve

- name: Start Jenkins agent container
  community.docker.docker_compose_v2:
    project_src: "{{ registry_compose_path }}"
    state: present
