- name: Setup Jenkins SSH Agents
  hosts: jenkins_ssh_agents
  vars_files:
    - ./files/become-pass.yml
    - ./files/id_rsa.yml
  become: true
  roles:
    # - docker-host
    - jenkins-ssh-agent-container

- name: Setup Registry
  hosts: registry
  vars_files:
    - ./files/become-pass.yml
  become: true
  roles:
    # - docker-host
    - registry
