# - name: Vagrantize!
#   hosts: siteholder
#   roles: [vagrantize]

# - name: Play prerequisites
#   hosts: vagrant_machines
#   become: true
#   roles: [prerequisites]   # installs docker, jre, python and other stuff

# ### CI/CD

- name: Setup Jenkins SSH Agents
  hosts: jenkins_ssh_agents
  vars_files:
    - ./vault/jenkins_id_rsa.yml
  become: true
  roles: [jenkins-ssh-agent-container]

- name: Jenkins master container
  hosts: jenkins_master
  vars_files:
    # - ./vault/become-pass.yml  # remote_user is nopasswd
    - ./vault/master-api.yml
    - ./vault/github-token.yml
    - ./vault/jks_pass.yml
    - ./vault/jenkins_id_rsa.yml
    - ./vault/tg_bot.yml
  become: true
  roles: [jenkins-master-container]

- name: Setup Registry (with jenkins agent for easier access from pipelines)
  hosts: registry
  become: true
  vars_files:
    - ./vault/jenkins_id_rsa.yml
  roles:
    - registry

### monitoring

- name: Monitoring master
  hosts: monitoring
  become: true
  vars_files:
    - ./vault/master-api.yml
  roles:
    - monitoring-master

- name: Monitored nodes
  hosts: monitored
  become: true
  roles:
    - monitored-node

