- name: Ensure compose directory is present
  ansible.builtin.file:
    path: "{{ node_compose_path }}"
    state: directory
    mode: "0777"

- name: Deploy Node Exporter Compose config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
  with_items:
    - src: node-compose.yml.j2
      dest: "{{ node_compose_path }}/docker-compose.yml"
    - src: templates/default_docker_compose_service.yml.j2
      dest: "{{ services_path }}/{{ compose_service_name }}"

- name: Run compose service
  ansible.builtin.systemd:
    name: "{{ compose_service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
