- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /usr/sbin/nologin

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz
    mode: "0755"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    remote_src: true
    dest: /tmp/

- name: Install binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-2.52.0.linux-amd64/{{ item }}"
    remote_src: true
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - prometheus
    - promtool

- name: Copy config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Create systemd service
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"

- name: Start and enable Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: restarted
    daemon_reload: true
